server:
  port: 80
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
        globalcors:
          cors-configurations:
            '[/**]':
              allowedOrigins: "*"
              allowedHeaders: "*"
              allowedMethods:
                - GET
                - POST
        routes:
          - id: user-authentication-service
            uri: http://localhost:8081
            predicates:
              - Path=/user-authentication/**
            filters:
              - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
              - name: CircuitBreaker
                args:
                  name: auth
                  fallbackUri: forward:/fallback/auth