server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    url: jdbc:postgresql://${POSTGRES}:${POSTGRES_PORT}/vehicle
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretkey: ${MOBILIZ_SECRETKEY}
  issuer: ${MOBILIZ_ISSUER}
  audience: ${MOBILIZ_AUDIENCE}