server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/UserMicroService
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secretkey: ${MOBILIZ_SECRETKEY}
  issuer: ${MOBILIZ_ISSUER}
  audience: ${MOBILIZ_AUDIENCE}